version = 1

exclude_patterns = [
  "bin/**",
  "**/node_modules/",
  "js/**/*.min.js"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[transformers]]
name = "prettier"